// GENERATED by scripts/bundle-functions.ts from supabase/functions/analyze-word — do not edit here.
// Paste the whole file as index.ts of the "analyze-word" Edge Function.

// supabase/functions/_shared/aiProviders.ts
var AI_PRESETS = {
  openai: { aiBaseUrl: "https://api.openai.com/v1", aiApiStyle: "responses", aiModel: "gpt-6-luna" },
  mistral: { aiBaseUrl: "https://api.mistral.ai/v1", aiApiStyle: "chat", aiModel: "mistral-large-latest" }
};
function resolveAiSettings(get) {
  const provider = (get("AI_PROVIDER") ?? "openai").trim().toLowerCase();
  const preset = AI_PRESETS[provider] ?? { aiBaseUrl: "", aiApiStyle: "chat", aiModel: "" };
  const style = get("AI_API_STYLE");
  return {
    aiApiKey: get("AI_API_KEY") ?? get("OPENAI_API_KEY") ?? "",
    aiBaseUrl: get("AI_BASE_URL") ?? preset.aiBaseUrl,
    aiApiStyle: style === "responses" || style === "chat" ? style : preset.aiApiStyle,
    aiModel: get("AI_MODEL") ?? preset.aiModel
  };
}

// supabase/functions/_shared/http.ts
function resolveServiceKey(get) {
  const direct = get("SUPABASE_SERVICE_ROLE_KEY") ?? get("SUPABASE_SECRET_KEY");
  if (direct)
    return direct;
  const raw = get("SUPABASE_SECRET_KEYS");
  if (!raw)
    return "";
  try {
    const parsed = JSON.parse(raw);
    const pick = (value) => {
      if (typeof value === "string")
        return value;
      if (value && typeof value === "object") {
        const record = value;
        for (const field of ["api_key", "key", "value", "secret"])
          if (typeof record[field] === "string")
            return record[field];
      }
      return "";
    };
    if (Array.isArray(parsed))
      return parsed.map(pick).find(Boolean) ?? "";
    if (parsed && typeof parsed === "object") {
      const record = parsed;
      return pick(record.default) || Object.values(record).map(pick).find(Boolean) || "";
    }
  } catch {
    return raw.trim();
  }
  return "";
}

class HttpError extends Error {
  status;
  code;
  extra;
  constructor(status, code, message, extra = {}) {
    super(message);
    this.status = status;
    this.code = code;
    this.extra = extra;
  }
}
function corsHeaders(req, env) {
  const origin = req.headers.get("origin") ?? "";
  const allowed = (env.allowedOrigins ?? "").split(",").map((s) => s.trim()).filter(Boolean);
  const any = allowed.length === 0 || allowed.includes("*");
  const allowOrigin = any ? "*" : allowed.includes(origin) ? origin : allowed[0];
  return {
    "Access-Control-Allow-Origin": allowOrigin,
    "Access-Control-Allow-Headers": "authorization, apikey, content-type, x-client-info",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin"
  };
}
function json(body, status, headers) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...headers, "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" }
  });
}
function errorResponse(err, headers) {
  if (err instanceof HttpError) {
    return json({ error: { code: err.code, message: err.message, ...err.extra } }, err.status, headers);
  }
  console.error("unhandled error", err instanceof Error ? err.message : String(err));
  return json({ error: { code: "internal", message: "Unexpected server error" } }, 500, headers);
}
async function readJsonBody(req, maxBytes) {
  const raw = await req.text();
  if (new TextEncoder().encode(raw).length > maxBytes) {
    throw new HttpError(413, "payload_too_large", "Request body is too large");
  }
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)) {
      return parsed;
    }
  } catch {}
  throw new HttpError(400, "invalid_json", "Body must be a JSON object");
}
async function requireUser(req, env, fetchImpl) {
  const header = req.headers.get("authorization") ?? "";
  const token = header.toLowerCase().startsWith("bearer ") ? header.slice(7).trim() : "";
  if (!token)
    throw new HttpError(401, "unauthorized", "Sign in required");
  let res;
  try {
    res = await fetchImpl(`${env.supabaseUrl}/auth/v1/user`, {
      headers: { Authorization: `Bearer ${token}`, apikey: env.serviceRoleKey }
    });
  } catch {
    throw new HttpError(503, "auth_unavailable", "Could not verify the session");
  }
  if (!res.ok)
    throw new HttpError(401, "unauthorized", "Session is invalid or expired");
  const user = await res.json();
  if (typeof user.id !== "string" || !user.id)
    throw new HttpError(401, "unauthorized", "Session is invalid");
  return { id: user.id };
}
function adminRest(env, fetchImpl) {
  const base = `${env.supabaseUrl}/rest/v1`;
  const headers = {
    apikey: env.serviceRoleKey,
    Authorization: `Bearer ${env.serviceRoleKey}`,
    "Content-Type": "application/json"
  };
  return {
    async select(path) {
      const res = await fetchImpl(`${base}/${path}`, { headers });
      if (!res.ok)
        throw new Error(`select ${path.split("?")[0]} failed: ${res.status}`);
      return await res.json();
    },
    async count(path) {
      const res = await fetchImpl(`${base}/${path}`, {
        method: "HEAD",
        headers: { ...headers, Prefer: "count=exact" }
      });
      if (!res.ok)
        throw new Error(`count ${path.split("?")[0]} failed: ${res.status}`);
      const total = (res.headers.get("content-range") ?? "").split("/")[1];
      const n = Number(total);
      if (!Number.isFinite(n))
        throw new Error("count: missing content-range");
      return n;
    },
    async insert(table, row, upsertOn) {
      const url = upsertOn ? `${base}/${table}?on_conflict=${upsertOn}` : `${base}/${table}`;
      const res = await fetchImpl(url, {
        method: "POST",
        headers: {
          ...headers,
          Prefer: upsertOn ? "resolution=merge-duplicates,return=minimal" : "return=minimal"
        },
        body: JSON.stringify(row)
      });
      if (!res.ok)
        throw new Error(`insert ${table} failed: ${res.status}`);
    }
  };
}

// supabase/functions/_shared/inputRules.ts
var MAX_INPUT_LENGTH = 40;
var ARTICLES = new Set(["der", "die", "das", "ein", "eine"]);
var REFLEXIVE = "sich";
var PERSIAN_ARABIC = /[؀-ۿݐ-ݿﭐ-﷿ﹰ-﻿]/;
var TOKEN = /^\p{Script=Latin}+(?:[-'’]\p{Script=Latin}+)*$/u;
var EDGE_PUNCTUATION = /^[\s"'„“”‚‘’«»()[\].,;:!?…]+|[\s"'„“”‚‘’«»()[\].,;:!?…]+$/g;
function cleanInput(raw) {
  return raw.normalize("NFC").replace(/[​-‏‪-‮⁦-⁩﻿]/g, "").replace(/\s+/g, " ").replace(EDGE_PUNCTUATION, "").trim();
}
function validateWordInput(raw) {
  if (typeof raw !== "string")
    return { ok: false, code: "empty" };
  const value = cleanInput(raw);
  if (value.length === 0)
    return { ok: false, code: "empty" };
  if (value.length > MAX_INPUT_LENGTH)
    return { ok: false, code: "too_long" };
  if (PERSIAN_ARABIC.test(value))
    return { ok: false, code: "wrong_script" };
  const tokens = value.split(" ");
  for (const token of tokens) {
    if (!TOKEN.test(token))
      return { ok: false, code: "invalid_characters" };
  }
  if (tokens.length > 2)
    return { ok: false, code: "multiple_words" };
  if (tokens.length === 2) {
    const lead = tokens[0].toLowerCase();
    if (!ARTICLES.has(lead) && lead !== REFLEXIVE) {
      return { ok: false, code: "multiple_words" };
    }
  }
  return { ok: true, value, cacheKey: value.toLocaleLowerCase("de") };
}

// supabase/functions/_shared/wordSchema.ts
var CONTENT_VERSION = 1;
var POS_VALUES = [
  "noun",
  "verb",
  "adjective",
  "adverb",
  "preposition",
  "conjunction",
  "pronoun",
  "article",
  "numeral",
  "interjection",
  "particle",
  "phrase",
  "other"
];
var CEFR_VALUES = ["A1", "A2", "B1", "B2", "C1", "C2"];
var EXAMPLE_LEVELS = ["easy", "medium", "hard"];
var ARTICLE_VALUES = ["der", "die", "das"];
var LIMITS = {
  lemma: 60,
  meanings: 3,
  examplesPerMeaning: 6,
  listItems: 8,
  collocations: 8,
  shortText: 120,
  sentence: 300,
  note: 600
};
var PERSIAN = /[؀-ۿ]/;
var LATIN = /\p{Script=Latin}/u;
var isRec = (v) => typeof v === "object" && v !== null && !Array.isArray(v);
function text(v) {
  return typeof v === "string" ? v.normalize("NFC").replace(/\s+/g, " ").trim() : "";
}
function optionalText(v) {
  const t = text(v);
  return t.length > 0 ? t : null;
}
function uniqueList(v) {
  if (!Array.isArray(v))
    return [];
  const seen = new Set;
  const out = [];
  for (const item of v) {
    const t = text(item);
    const key = t.toLocaleLowerCase("de");
    if (t && !seen.has(key)) {
      seen.add(key);
      out.push(t);
    }
  }
  return out;
}
function validateWordContent(input, options) {
  const issues = [];
  const add = (path, code) => issues.push({ path, code });
  if (!isRec(input))
    return { ok: false, issues: [{ path: "", code: "required" }] };
  const lemma = text(input.lemma);
  if (!lemma)
    add("lemma", "required");
  else if (lemma.length > LIMITS.lemma)
    add("lemma", "too_long");
  else if (!LATIN.test(lemma) || PERSIAN.test(lemma))
    add("lemma", "wrong_script");
  const pos = input.pos;
  if (!POS_VALUES.includes(pos))
    add("pos", "invalid_value");
  let cefr = null;
  if (input.cefr !== null && input.cefr !== undefined && input.cefr !== "") {
    if (CEFR_VALUES.includes(input.cefr))
      cefr = input.cefr;
    else
      add("cefr", "invalid_value");
  } else if (options.mode === "ai") {
    add("cefr", "required");
  }
  const ipa = optionalText(input.ipa);
  if (ipa && ipa.length > LIMITS.shortText)
    add("ipa", "too_long");
  const meanings = [];
  const rawMeanings = Array.isArray(input.meanings) ? input.meanings : [];
  if (rawMeanings.length === 0)
    add("meanings", "required");
  if (rawMeanings.length > LIMITS.meanings)
    add("meanings", "too_many");
  rawMeanings.slice(0, LIMITS.meanings).forEach((raw, i) => {
    const p = `meanings.${i}`;
    if (!isRec(raw))
      return add(p, "invalid_value");
    const translation = text(raw.translation);
    if (!translation)
      add(`${p}.translation`, "required");
    else if (translation.length > LIMITS.shortText)
      add(`${p}.translation`, "too_long");
    else if (!PERSIAN.test(translation))
      add(`${p}.translation`, "wrong_script");
    const note = optionalText(raw.note);
    if (note && note.length > LIMITS.note)
      add(`${p}.note`, "too_long");
    const examples = [];
    const rawExamples = Array.isArray(raw.examples) ? raw.examples : [];
    if (rawExamples.length > LIMITS.examplesPerMeaning)
      add(`${p}.examples`, "too_many");
    rawExamples.slice(0, LIMITS.examplesPerMeaning).forEach((ex, j) => {
      const q = `${p}.examples.${j}`;
      if (!isRec(ex))
        return add(q, "invalid_value");
      const level = ex.level;
      if (!EXAMPLE_LEVELS.includes(level))
        add(`${q}.level`, "invalid_value");
      const de = text(ex.de);
      const fa = text(ex.fa);
      if (!de)
        add(`${q}.de`, "required");
      else if (de.length > LIMITS.sentence)
        add(`${q}.de`, "too_long");
      else if (!LATIN.test(de) || PERSIAN.test(de))
        add(`${q}.de`, "wrong_script");
      if (!fa)
        add(`${q}.fa`, "required");
      else if (fa.length > LIMITS.sentence)
        add(`${q}.fa`, "too_long");
      else if (!PERSIAN.test(fa))
        add(`${q}.fa`, "wrong_script");
      examples.push({ level, de, fa });
    });
    if (options.mode === "ai") {
      const levels = new Set(examples.map((e) => e.level));
      if (examples.length !== EXAMPLE_LEVELS.length || levels.size !== EXAMPLE_LEVELS.length) {
        add(`${p}.examples`, "missing_levels");
      }
    }
    meanings.push({ translation, note, examples });
  });
  let noun = null;
  if (pos === "noun") {
    if (!isRec(input.noun))
      add("noun", "required");
    else {
      const raw = input.noun;
      const pluralOnly = raw.pluralOnly === true;
      let article = null;
      if (ARTICLE_VALUES.includes(raw.article))
        article = raw.article;
      else if (!pluralOnly)
        add("noun.article", raw.article ? "invalid_value" : "required");
      const plural = optionalText(raw.plural);
      const genitive = optionalText(raw.genitive);
      if (plural && plural.length > LIMITS.shortText)
        add("noun.plural", "too_long");
      if (genitive && genitive.length > LIMITS.shortText)
        add("noun.genitive", "too_long");
      noun = { article: pluralOnly && !article ? "die" : article, plural, genitive, pluralOnly };
    }
  }
  let verb = null;
  if (pos === "verb") {
    if (!isRec(input.verb))
      add("verb", "required");
    else {
      const raw = input.verb;
      const six = (key) => {
        const list = Array.isArray(raw[key]) ? raw[key].map(text) : [];
        if (list.length !== 6 || list.some((f) => !f))
          add(`verb.${key}`, list.length ? "invalid_value" : "required");
        else if (list.some((f) => f.length > LIMITS.shortText || PERSIAN.test(f)))
          add(`verb.${key}`, "invalid_value");
        return [0, 1, 2, 3, 4, 5].map((i) => list[i] ?? "");
      };
      const auxiliary = raw.auxiliary === "sein" ? "sein" : raw.auxiliary === "haben" ? "haben" : null;
      if (!auxiliary)
        add("verb.auxiliary", "invalid_value");
      const reflexive = raw.reflexive === "accusative" || raw.reflexive === "dative" || raw.reflexive === "none" ? raw.reflexive : null;
      if (!reflexive)
        add("verb.reflexive", "invalid_value");
      const partizip2 = text(raw.partizip2);
      if (!partizip2)
        add("verb.partizip2", "required");
      else if (partizip2.length > LIMITS.shortText)
        add("verb.partizip2", "too_long");
      const imp = isRec(raw.imperativ) ? raw.imperativ : {};
      const imperativ = { du: text(imp.du), ihr: text(imp.ihr), Sie: text(imp.Sie) };
      const filled = [imperativ.du, imperativ.ihr, imperativ.Sie].filter(Boolean).length;
      if (filled !== 0 && filled !== 3)
        add("verb.imperativ", "invalid_value");
      const government = optionalText(raw.government);
      if (government && government.length > LIMITS.shortText)
        add("verb.government", "too_long");
      verb = {
        separable: raw.separable === true,
        auxiliary: auxiliary ?? "haben",
        reflexive: reflexive ?? "none",
        irregular: raw.irregular === true,
        partizip2,
        government,
        praesens: six("praesens"),
        praeteritum: six("praeteritum"),
        konjunktiv1: six("konjunktiv1"),
        konjunktiv2: six("konjunktiv2"),
        imperativ
      };
    }
  }
  let adjective = null;
  if (pos === "adjective" && isRec(input.adjective)) {
    const comparative = optionalText(input.adjective.comparative);
    const superlative = optionalText(input.adjective.superlative);
    if (comparative && comparative.length > LIMITS.shortText)
      add("adjective.comparative", "too_long");
    if (superlative && superlative.length > LIMITS.shortText)
      add("adjective.superlative", "too_long");
    if (comparative || superlative)
      adjective = { comparative, superlative };
  }
  const synonyms = uniqueList(input.synonyms);
  const antonyms = uniqueList(input.antonyms);
  if (synonyms.length > LIMITS.listItems)
    add("synonyms", "too_many");
  if (antonyms.length > LIMITS.listItems)
    add("antonyms", "too_many");
  if ([...synonyms, ...antonyms].some((s) => s.length > LIMITS.shortText))
    add("synonyms", "too_long");
  const collocations = [];
  const rawCollocations = Array.isArray(input.collocations) ? input.collocations : [];
  if (rawCollocations.length > LIMITS.collocations)
    add("collocations", "too_many");
  rawCollocations.slice(0, LIMITS.collocations).forEach((raw, i) => {
    if (!isRec(raw))
      return add(`collocations.${i}`, "invalid_value");
    const de = text(raw.de);
    const fa = text(raw.fa);
    if (!de && !fa)
      return;
    if (!de)
      add(`collocations.${i}.de`, "required");
    if (!fa)
      add(`collocations.${i}.fa`, "required");
    if (de.length > LIMITS.sentence || fa.length > LIMITS.sentence)
      add(`collocations.${i}`, "too_long");
    collocations.push({ de, fa });
  });
  const notes = optionalText(input.notes);
  if (notes && notes.length > LIMITS.note)
    add("notes", "too_long");
  if (issues.length > 0)
    return { ok: false, issues };
  return {
    ok: true,
    value: {
      version: CONTENT_VERSION,
      lemma,
      pos,
      cefr,
      ipa,
      meanings,
      noun,
      verb,
      adjective,
      synonyms,
      antonyms,
      collocations,
      notes
    }
  };
}

// supabase/functions/_shared/prompt.ts
var PROMPT_VERSION = "word_analysis_v1";
var SUPPORTED_PAIRS = [{ target: "de", native: "fa" }];
function isSupportedPair(pair) {
  return SUPPORTED_PAIRS.some((p) => p.target === pair.target && p.native === pair.native);
}
var AI_STATUS = ["ok", "not_a_word", "wrong_language", "misspelled"];
var SYSTEM_DE_FA = `You are a careful German lexicographer and teacher writing vocabulary cards for native Persian (Farsi) speakers who are learning German.

You receive ONE German word typed by a learner. Return a single JSON object that follows the provided schema exactly.

STEP 1 — decide "status":
- "ok": the input is a real German word (any inflected form counts).
- "misspelled": it is clearly a typo of a German word (missing umlaut, swapped letters). Put the corrected word in "suggestion". Do not analyse it.
- "wrong_language": it is a word of another language and not used in German.
- "not_a_word": random letters, a name with no dictionary meaning, or more than one independent word.
For every status except "ok": lemma = "", meanings = [], noun/verb/adjective = null, lists = [], other text fields null, pos = "other", cefr = "A1".

STEP 2 — when status is "ok":
- "lemma": the dictionary form. Nouns: nominative singular WITHOUT article, capitalised ("Tisch"). Verbs: infinitive ("aufgeben"); truly reflexive verbs as "sich freuen". Adjectives: base form.
- If the learner typed an inflected form ("ging", "Häuser", "besser"), analyse the lemma and explain the relation in one short Persian sentence in "input_note". Otherwise "input_note" is null.
- "pos": the most common part of speech of this word.
- "cefr": the level at which a learner typically meets this word (your best estimate).
- "ipa": IPA transcription of the lemma in standard German, without slashes or brackets.
- "meanings": the 1 to 3 most common, practically useful meanings, most important first. Add a second or third meaning ONLY when it is genuinely common in everyday German. This is not a dictionary dump.
  - "translation": natural Persian equivalent(s), short (a few words, comma-separated synonyms allowed).
  - "note": optional short Persian hint that tells this meaning apart (register, context). null if not needed.
  - "examples": EXACTLY three, one of each level:
      "easy"   — A1/A2, short main clause, present tense.
      "medium" — B1, a longer sentence, e.g. perfect tense or a subordinate clause.
      "hard"   — B2+, natural idiomatic usage.
    Each example uses the word in THIS meaning, is natural, correct German a native speaker would say, and has a faithful natural Persian translation in "fa" (not word-for-word).
- "noun": only for nouns, else null. "article" is der/die/das. "plural" is the nominative plural WITHOUT article ("Tische"), null if the noun has no plural. "genitive" is the genitive singular without article ("Tisches"). For plural-only nouns (Eltern, Leute): plural_only = true, article = "die", plural = null.
- "verb": only for verbs, else null.
  - "separable": true for trennbare Verben.
  - "auxiliary": "haben" or "sein" (the usual one for the Perfekt).
  - "reflexive": "accusative" (sich freuen → ich freue mich), "dative" (sich etwas vorstellen → ich stelle mir vor) or "none".
  - "irregular": true for strong and mixed verbs.
  - "partizip2": e.g. "aufgegeben".
  - "government": fixed preposition and case if the verb has one worth learning, e.g. "auf + Akkusativ"; else null.
  - "praesens", "praeteritum", "konjunktiv1", "konjunktiv2": EXACTLY six forms each, in this order: ich, du, er/sie/es, wir, ihr, sie/Sie. Give the verb form WITHOUT the subject pronoun. Separable verbs in main-clause order ("gebe auf"). Reflexive verbs with their pronoun ("freue mich"). konjunktiv1 = Konjunktiv I Präsens ("gebe auf", "gebest auf", "gebe auf", ...). konjunktiv2 = Konjunktiv II Präteritum (the synthetic form: "gäbe auf", "ginge", "machte"), not the würde-form.
  - "imperativ": full forms with exclamation mark: du "Gib auf!", ihr "Gebt auf!", Sie "Geben Sie auf!". For verbs without an imperative (modal verbs) use three empty strings.
  Do NOT produce compound tenses (Perfekt, Futur …); the app builds them itself.
- "adjective": only for adjectives, else null. "comparative"/"superlative" ("schneller" / "am schnellsten"); null for adjectives that cannot be compared.
- "synonyms" / "antonyms": 0 to 4 common German words each, nouns with article. Empty list when there is none that a learner should know.
- "collocations": 2 to 4 very common word combinations with Persian translation.
- "learner_note": at most two short Persian sentences with the single most useful tip (a typical mistake of Persian speakers, a false friend, a confusable word). null if there is nothing worth saying.

LANGUAGE RULES:
- All Persian text is in modern standard written Persian, in Persian script, with correct half-spaces (نیم‌فاصله). No transliteration, no English.
- All German text follows current standard orthography (ß, umlauts, noun capitalisation).
- Never invent words, forms or meanings. If you are unsure whether a form exists, choose the standard form found in Duden.`;
function buildMessages(pair, word) {
  if (!isSupportedPair(pair))
    throw new Error(`unsupported language pair ${pair.target}/${pair.native}`);
  return { system: SYSTEM_DE_FA, user: `German word: ${JSON.stringify(word)}` };
}
function buildRepairMessage(issues) {
  const list = issues.slice(0, 12).map((i) => `- ${i.path || "(root)"}: ${i.code}`).join(`
`);
  return `Your previous JSON failed validation:
${list}
Return the complete corrected JSON object for the same word. Follow every rule of the instructions.`;
}
var nullable = (schema) => ({ anyOf: [schema, { type: "null" }] });
var str = { type: "string" };
var strOrNull = { type: ["string", "null"] };
var strList = { type: "array", items: str };
var obj = (properties) => ({
  type: "object",
  properties,
  required: Object.keys(properties),
  additionalProperties: false
});
var AI_OUTPUT_SCHEMA = obj({
  status: { type: "string", enum: [...AI_STATUS] },
  suggestion: strOrNull,
  input_note: strOrNull,
  lemma: str,
  pos: { type: "string", enum: [...POS_VALUES] },
  cefr: { type: "string", enum: [...CEFR_VALUES] },
  ipa: strOrNull,
  meanings: {
    type: "array",
    items: obj({
      translation: str,
      note: strOrNull,
      examples: {
        type: "array",
        items: obj({ level: { type: "string", enum: [...EXAMPLE_LEVELS] }, de: str, fa: str })
      }
    })
  },
  noun: nullable(obj({
    article: { type: "string", enum: [...ARTICLE_VALUES] },
    plural: strOrNull,
    genitive: strOrNull,
    plural_only: { type: "boolean" }
  })),
  verb: nullable(obj({
    separable: { type: "boolean" },
    auxiliary: { type: "string", enum: ["haben", "sein"] },
    reflexive: { type: "string", enum: ["none", "accusative", "dative"] },
    irregular: { type: "boolean" },
    partizip2: str,
    government: strOrNull,
    praesens: strList,
    praeteritum: strList,
    konjunktiv1: strList,
    konjunktiv2: strList,
    imperativ: obj({ du: str, ihr: str, Sie: str })
  })),
  adjective: nullable(obj({ comparative: strOrNull, superlative: strOrNull })),
  synonyms: strList,
  antonyms: strList,
  collocations: { type: "array", items: obj({ de: str, fa: str }) },
  learner_note: strOrNull
});
function aiOutputToContentInput(raw) {
  const noun = raw.noun;
  return {
    lemma: raw.lemma,
    pos: raw.pos,
    cefr: raw.cefr,
    ipa: raw.ipa,
    meanings: raw.meanings,
    noun: noun ? { article: noun.article, plural: noun.plural, genitive: noun.genitive, pluralOnly: noun.plural_only } : null,
    verb: raw.verb,
    adjective: raw.adjective,
    synonyms: raw.synonyms,
    antonyms: raw.antonyms,
    collocations: raw.collocations,
    notes: raw.learner_note
  };
}

// supabase/functions/_shared/analyzeWord.ts
var DEFAULTS = { perMinute: 6, perDay: 80, globalDay: 400, timeoutMs: 60000 };
var MAX_BODY_BYTES = 2000;
var MAX_OUTPUT_TOKENS = 8000;
async function handleAnalyzeWord(req, env, fetchImpl = fetch, sleep = (ms) => new Promise((r) => setTimeout(r, ms))) {
  const cors = corsHeaders(req, env);
  if (req.method === "OPTIONS")
    return new Response(null, { status: 204, headers: cors });
  try {
    if (req.method !== "POST")
      throw new HttpError(405, "method_not_allowed", "Use POST");
    if (!env.supabaseUrl || !env.serviceRoleKey)
      throw new HttpError(500, "not_configured", "Server is not configured");
    const user = await requireUser(req, env, fetchImpl);
    const body = await readJsonBody(req, MAX_BODY_BYTES);
    const input = validateWordInput(body.word);
    if (!input.ok)
      throw new HttpError(400, "invalid_input", "The word is not valid", { reason: input.code });
    const pair = {
      target: typeof body.targetLanguage === "string" ? body.targetLanguage : "de",
      native: typeof body.nativeLanguage === "string" ? body.nativeLanguage : "fa"
    };
    if (!isSupportedPair(pair))
      throw new HttpError(400, "unsupported_language", "This language pair is not available yet");
    const force = body.force === true;
    const db = adminRest(env, fetchImpl);
    const started = Date.now();
    const log = (status, extra = {}) => db.insert("ai_generation_logs", {
      user_id: user.id,
      kind: "analyze_word",
      input: input.value,
      status,
      prompt_version: PROMPT_VERSION,
      model: env.aiModel,
      duration_ms: Date.now() - started,
      ...extra
    }).catch((e) => console.error("log failed", e instanceof Error ? e.message : e));
    const cacheFilter = `target_language=eq.${pair.target}&native_language=eq.${pair.native}` + `&input_key=eq.${encodeURIComponent(input.cacheKey)}&prompt_version=eq.${PROMPT_VERSION}`;
    if (!force) {
      const rows = await db.select(`ai_word_cache?${cacheFilter}&select=result&limit=1`).catch(() => []);
      const hit = rows[0]?.result;
      if (hit && isUsableCachedResult(hit)) {
        await log("cache_hit");
        return json({ ...hit, cached: true }, 200, cors);
      }
    }
    await enforceRateLimits(db, user.id, env);
    if (!env.aiApiKey || !env.aiModel || !env.aiBaseUrl)
      throw new HttpError(500, "not_configured", "The AI service is not configured");
    let outcome;
    try {
      outcome = await generate(input.value, pair, env, fetchImpl, sleep);
    } catch (err) {
      const code = err instanceof HttpError ? err.code : "internal";
      await log("error", { error_code: code });
      throw err;
    }
    const { result, usage } = outcome;
    await log(result.status === "ok" ? "ok" : "rejected", {
      input_tokens: usage.inputTokens,
      output_tokens: usage.outputTokens
    });
    await db.insert("ai_word_cache", {
      target_language: pair.target,
      native_language: pair.native,
      input_key: input.cacheKey,
      prompt_version: PROMPT_VERSION,
      model: env.aiModel,
      result,
      updated_at: new Date().toISOString()
    }, "target_language,native_language,input_key,prompt_version").catch((e) => console.error("cache write failed", e instanceof Error ? e.message : e));
    return json(result, 200, cors);
  } catch (err) {
    return errorResponse(err, cors);
  }
}
function isUsableCachedResult(hit) {
  if (hit.status !== "ok")
    return AI_STATUS.includes(hit.status);
  return validateWordContent(hit.content, { mode: "ai" }).ok;
}
async function enforceRateLimits(db, userId, env) {
  const perMinute = env.perMinuteLimit ?? DEFAULTS.perMinute;
  const perDay = env.perDayLimit ?? DEFAULTS.perDay;
  const globalDay = env.globalDayLimit ?? DEFAULTS.globalDay;
  const fresh = "status=in.(ok,rejected,error)&select=id";
  const minuteAgo = new Date(Date.now() - 60000).toISOString();
  const dayAgo = new Date(Date.now() - 86400000).toISOString();
  let lastMinute, lastDay, allDay;
  try {
    [lastMinute, lastDay, allDay] = await Promise.all([
      db.count(`ai_generation_logs?user_id=eq.${userId}&created_at=gte.${minuteAgo}&${fresh}`),
      db.count(`ai_generation_logs?user_id=eq.${userId}&created_at=gte.${dayAgo}&${fresh}`),
      db.count(`ai_generation_logs?created_at=gte.${dayAgo}&${fresh}`)
    ]);
  } catch (e) {
    console.error("rate limit check failed", e instanceof Error ? e.message : e);
    throw new HttpError(503, "rate_limit_unavailable", "Usage could not be checked, try again shortly");
  }
  if (lastMinute >= perMinute) {
    throw new HttpError(429, "rate_limited", "Too many requests", { scope: "minute", retryAfterSeconds: 60 });
  }
  if (lastDay >= perDay) {
    throw new HttpError(429, "rate_limited", "Daily limit reached", { scope: "day", retryAfterSeconds: 3600 });
  }
  if (allDay >= globalDay) {
    throw new HttpError(429, "rate_limited", "Daily limit reached", { scope: "global", retryAfterSeconds: 3600 });
  }
}
async function generate(word, pair, env, fetchImpl, sleep) {
  const { system, user } = buildMessages(pair, word);
  const messages = [
    { role: "system", content: system },
    { role: "user", content: user }
  ];
  const usage = { inputTokens: 0, outputTokens: 0 };
  let lastIssues = [];
  for (let attempt = 0;attempt < 2; attempt++) {
    const answer = await callModel(messages, env, fetchImpl, sleep);
    usage.inputTokens += answer.usage.inputTokens;
    usage.outputTokens += answer.usage.outputTokens;
    const parsed = interpret(answer.text, env.aiModel);
    if (parsed.ok)
      return { result: parsed.result, usage };
    lastIssues = parsed.issues;
    messages.push({ role: "assistant", content: answer.text });
    messages.push({ role: "user", content: buildRepairMessage(parsed.issues) });
  }
  console.error("invalid AI output after repair", JSON.stringify(lastIssues.slice(0, 8)));
  throw new HttpError(502, "ai_invalid_output", "The AI answer was not usable");
}
function interpret(text, model) {
  let raw;
  try {
    raw = JSON.parse(text);
  } catch {
    return { ok: false, issues: [{ path: "", code: "invalid_value" }] };
  }
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    return { ok: false, issues: [{ path: "", code: "invalid_value" }] };
  }
  const data = raw;
  const status = data.status;
  if (!AI_STATUS.includes(status))
    return { ok: false, issues: [{ path: "status", code: "invalid_value" }] };
  if (status === "misspelled") {
    const suggestion = validateWordInput(data.suggestion);
    if (!suggestion.ok)
      return { ok: true, result: { status: "not_a_word", cached: false } };
    return { ok: true, result: { status, suggestion: suggestion.value, cached: false } };
  }
  if (status !== "ok")
    return { ok: true, result: { status, cached: false } };
  const checked = validateWordContent(aiOutputToContentInput(data), { mode: "ai" });
  if (!checked.ok)
    return { ok: false, issues: checked.issues };
  const inputNote = typeof data.input_note === "string" && data.input_note.trim() ? data.input_note.trim().slice(0, 300) : null;
  return {
    ok: true,
    result: { status: "ok", content: checked.value, inputNote, promptVersion: PROMPT_VERSION, model, cached: false }
  };
}
async function callModel(messages, env, fetchImpl, sleep) {
  const base = env.aiBaseUrl.replace(/\/+$/, "");
  const format = { name: "word_analysis", strict: true, schema: AI_OUTPUT_SCHEMA };
  const url = env.aiApiStyle === "chat" ? `${base}/chat/completions` : `${base}/responses`;
  const payload = JSON.stringify(env.aiApiStyle === "chat" ? {
    model: env.aiModel,
    messages,
    max_tokens: MAX_OUTPUT_TOKENS,
    response_format: { type: "json_schema", json_schema: format }
  } : {
    model: env.aiModel,
    input: messages,
    max_output_tokens: MAX_OUTPUT_TOKENS,
    store: false,
    text: { format: { type: "json_schema", ...format } }
  });
  const maxAttempts = 3;
  let lastError = new HttpError(502, "ai_unavailable", "The AI service did not answer");
  for (let attempt = 1;attempt <= maxAttempts; attempt++) {
    const controller = new AbortController;
    const timer = setTimeout(() => controller.abort(), env.timeoutMs ?? DEFAULTS.timeoutMs);
    let res = null;
    let body = "";
    try {
      res = await fetchImpl(url, {
        method: "POST",
        headers: { Authorization: `Bearer ${env.aiApiKey}`, "Content-Type": "application/json" },
        body: payload,
        signal: controller.signal
      });
      body = await res.text();
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") {
        throw new HttpError(504, "ai_timeout", "The AI service took too long");
      }
      res = null;
      lastError = new HttpError(502, "ai_unavailable", "The AI service could not be reached");
    } finally {
      clearTimeout(timer);
    }
    if (res) {
      if (res.ok) {
        let data;
        try {
          data = JSON.parse(body);
        } catch {
          throw new HttpError(502, "ai_invalid_output", "The AI answer was not readable");
        }
        return env.aiApiStyle === "chat" ? extractChatText(data) : extractText(data);
      }
      console.error("ai provider error", res.status, body.slice(0, 300));
      if (res.status === 401 || res.status === 403) {
        throw new HttpError(500, "not_configured", "The AI key was rejected");
      }
      if (res.status === 404 || res.status === 400 && /model/i.test(body)) {
        throw new HttpError(500, "not_configured", "The configured AI model is not available");
      }
      if ((res.status === 429 || res.status === 402) && /insufficient_quota|billing|credit|payment/i.test(body)) {
        throw new HttpError(503, "ai_quota_exhausted", "The AI account has no credit left");
      }
      lastError = new HttpError(502, "ai_unavailable", "The AI service returned an error");
      if (res.status !== 429 && res.status < 500)
        throw lastError;
    }
    if (attempt < maxAttempts)
      await sleep(400 * 2 ** (attempt - 1));
  }
  throw lastError;
}
function extractText(data) {
  const usageRaw = data.usage ?? {};
  const usage = {
    inputTokens: Number(usageRaw.input_tokens) || 0,
    outputTokens: Number(usageRaw.output_tokens) || 0
  };
  if (data.status === "incomplete")
    throw new HttpError(502, "ai_invalid_output", "The AI answer was cut off");
  const output = Array.isArray(data.output) ? data.output : [];
  for (const item of output) {
    if (item.type !== "message" || !Array.isArray(item.content))
      continue;
    for (const part of item.content) {
      if (part.type === "refusal")
        throw new HttpError(502, "ai_invalid_output", "The AI declined to answer");
      if (part.type === "output_text" && typeof part.text === "string")
        return { text: part.text, usage };
    }
  }
  throw new HttpError(502, "ai_invalid_output", "The AI answer was empty");
}
function extractChatText(data) {
  const usageRaw = data.usage ?? {};
  const usage = {
    inputTokens: Number(usageRaw.prompt_tokens) || 0,
    outputTokens: Number(usageRaw.completion_tokens) || 0
  };
  const choice = Array.isArray(data.choices) ? data.choices[0] : null;
  if (!choice)
    throw new HttpError(502, "ai_invalid_output", "The AI answer was empty");
  if (choice.finish_reason === "length")
    throw new HttpError(502, "ai_invalid_output", "The AI answer was cut off");
  const message = choice.message ?? {};
  if (typeof message.refusal === "string" && message.refusal)
    throw new HttpError(502, "ai_invalid_output", "The AI declined to answer");
  const content = message.content;
  if (typeof content === "string" && content.trim())
    return { text: content, usage };
  if (Array.isArray(content)) {
    const text = content.map((part) => typeof part.text === "string" ? part.text : "").join("");
    if (text.trim())
      return { text, usage };
  }
  throw new HttpError(502, "ai_invalid_output", "The AI answer was empty");
}

// supabase/functions/analyze-word/index.ts
var num = (name) => {
  const raw = Deno.env.get(name);
  const n = raw ? Number(raw) : NaN;
  return Number.isFinite(n) && n > 0 ? n : undefined;
};
Deno.serve((req) => handleAnalyzeWord(req, {
  supabaseUrl: Deno.env.get("SUPABASE_URL") ?? "",
  serviceRoleKey: resolveServiceKey((name) => Deno.env.get(name) || undefined),
  allowedOrigins: Deno.env.get("ALLOWED_ORIGINS") ?? "",
  ...resolveAiSettings((name) => Deno.env.get(name) || undefined),
  perMinuteLimit: num("AI_LIMIT_PER_MINUTE"),
  perDayLimit: num("AI_LIMIT_PER_DAY"),
  globalDayLimit: num("AI_LIMIT_GLOBAL_PER_DAY"),
  timeoutMs: num("AI_TIMEOUT_MS")
}));
