// GENERATED by scripts/bundle-functions.ts from supabase/functions/delete-account — do not edit here.
// Paste the whole file as index.ts of the "delete-account" Edge Function.

// supabase/functions/_shared/http.ts
function resolveServiceKey(get) {
  const direct = get("SUPABASE_SERVICE_ROLE_KEY") ?? get("SUPABASE_SECRET_KEY");
  if (direct)
    return direct;
  const raw = get("SUPABASE_SECRET_KEYS");
  if (!raw)
    return "";
  try {
    const parsed = JSON.parse(raw);
    const pick = (value) => {
      if (typeof value === "string")
        return value;
      if (value && typeof value === "object") {
        const record = value;
        for (const field of ["api_key", "key", "value", "secret"])
          if (typeof record[field] === "string")
            return record[field];
      }
      return "";
    };
    if (Array.isArray(parsed))
      return parsed.map(pick).find(Boolean) ?? "";
    if (parsed && typeof parsed === "object") {
      const record = parsed;
      return pick(record.default) || Object.values(record).map(pick).find(Boolean) || "";
    }
  } catch {
    return raw.trim();
  }
  return "";
}

class HttpError extends Error {
  status;
  code;
  extra;
  constructor(status, code, message, extra = {}) {
    super(message);
    this.status = status;
    this.code = code;
    this.extra = extra;
  }
}
function corsHeaders(req, env) {
  const origin = req.headers.get("origin") ?? "";
  const allowed = (env.allowedOrigins ?? "").split(",").map((s) => s.trim()).filter(Boolean);
  const any = allowed.length === 0 || allowed.includes("*");
  const allowOrigin = any ? "*" : allowed.includes(origin) ? origin : allowed[0];
  return {
    "Access-Control-Allow-Origin": allowOrigin,
    "Access-Control-Allow-Headers": "authorization, apikey, content-type, x-client-info",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin"
  };
}
function json(body, status, headers) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...headers, "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" }
  });
}
function errorResponse(err, headers) {
  if (err instanceof HttpError) {
    return json({ error: { code: err.code, message: err.message, ...err.extra } }, err.status, headers);
  }
  console.error("unhandled error", err instanceof Error ? err.message : String(err));
  return json({ error: { code: "internal", message: "Unexpected server error" } }, 500, headers);
}
async function readJsonBody(req, maxBytes) {
  const raw = await req.text();
  if (new TextEncoder().encode(raw).length > maxBytes) {
    throw new HttpError(413, "payload_too_large", "Request body is too large");
  }
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)) {
      return parsed;
    }
  } catch {}
  throw new HttpError(400, "invalid_json", "Body must be a JSON object");
}
async function requireUser(req, env, fetchImpl) {
  const header = req.headers.get("authorization") ?? "";
  const token = header.toLowerCase().startsWith("bearer ") ? header.slice(7).trim() : "";
  if (!token)
    throw new HttpError(401, "unauthorized", "Sign in required");
  let res;
  try {
    res = await fetchImpl(`${env.supabaseUrl}/auth/v1/user`, {
      headers: { Authorization: `Bearer ${token}`, apikey: env.serviceRoleKey }
    });
  } catch {
    throw new HttpError(503, "auth_unavailable", "Could not verify the session");
  }
  if (!res.ok)
    throw new HttpError(401, "unauthorized", "Session is invalid or expired");
  const user = await res.json();
  if (typeof user.id !== "string" || !user.id)
    throw new HttpError(401, "unauthorized", "Session is invalid");
  return { id: user.id };
}

// supabase/functions/_shared/deleteAccount.ts
var DELETE_CONFIRMATION = "DELETE";
async function handleDeleteAccount(req, env, fetchImpl = fetch) {
  const cors = corsHeaders(req, env);
  if (req.method === "OPTIONS")
    return new Response(null, { status: 204, headers: cors });
  try {
    if (req.method !== "POST")
      throw new HttpError(405, "method_not_allowed", "Use POST");
    if (!env.supabaseUrl || !env.serviceRoleKey)
      throw new HttpError(500, "not_configured", "Server is not configured");
    const user = await requireUser(req, env, fetchImpl);
    const body = await readJsonBody(req, 500);
    if (body.confirm !== DELETE_CONFIRMATION) {
      throw new HttpError(400, "confirmation_required", "Deletion must be confirmed explicitly");
    }
    const res = await fetchImpl(`${env.supabaseUrl}/auth/v1/admin/users/${user.id}`, {
      method: "DELETE",
      headers: { apikey: env.serviceRoleKey, Authorization: `Bearer ${env.serviceRoleKey}` }
    });
    if (!res.ok) {
      console.error("delete user failed", res.status);
      throw new HttpError(502, "delete_failed", "The account could not be deleted");
    }
    return json({ deleted: true }, 200, cors);
  } catch (err) {
    return errorResponse(err, cors);
  }
}

// supabase/functions/delete-account/index.ts
Deno.serve((req) => handleDeleteAccount(req, {
  supabaseUrl: Deno.env.get("SUPABASE_URL") ?? "",
  serviceRoleKey: resolveServiceKey((name) => Deno.env.get(name) || undefined),
  allowedOrigins: Deno.env.get("ALLOWED_ORIGINS") ?? ""
}));
