/**
 * Bundles each Edge Function into ONE file under deploy/, for pasting into the
 * Supabase dashboard editor (Edge Functions → Deploy a new function → Via Editor).
 * With the Supabase CLI this step is not needed: `supabase functions deploy` bundles by itself.
 */
import { mkdir, readdir, rm } from 'node:fs/promises'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')
const out = join(root, 'deploy')
await rm(out, { recursive: true, force: true })
await mkdir(out, { recursive: true })

const functions = (await readdir(join(root, 'supabase/functions'), { withFileTypes: true })).filter((d) => d.isDirectory() && !d.name.startsWith('_'))
for (const fn of functions) {
  const result = await Bun.build({
    entrypoints: [join(root, 'supabase/functions', fn.name, 'index.ts')],
    target: 'browser',
    format: 'esm',
    minify: false,
  })
  if (!result.success) {
    for (const log of result.logs) console.error(log)
    process.exit(1)
  }
  const code = await result.outputs[0]!.text()
  const banner = `// GENERATED by scripts/bundle-functions.ts from supabase/functions/${fn.name} — do not edit here.\n// Paste the whole file as index.ts of the "${fn.name}" Edge Function.\n\n`
  await Bun.write(join(out, `${fn.name}.ts`), banner + code)
  console.log(`deploy/${fn.name}.ts  ${(code.length / 1024).toFixed(1)} kB`)
}
